apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgdatabases.taka.edu.pl
spec:
  group: taka.edu.pl
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
                username:
                  type: string
                password:
                  type: string
                serviceName:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
                  enum: [Pending, Created, Failed]
      additionalPrinterColumns:
      - name: STATUS
        type: string
        jsonPath: .status.state
  scope: Namespaced
  names:
    plural: pgdatabases
    singular: pgdatabase
    kind: PGDatabase
    shortNames:
      - pgdb
